feat: manage template scans and api_gateway HSTS
cds-snc/scan-websites pull request #137
Opened 2021-09-24 19:57 UTC by mohamed-cds

Can now update template scans and api gateway will return the HSTS header when sending responses.

2021-09-26 19:03 UTC, patheard commented on terragrunt/aws/api/api_gateway.tf
> +    "method.response.header.Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload"
Would it be worth [ramping up `max-age` in increments](https://hstspreload.org/#deployment-recommendations) to make sure it doesn't break anything?

2021-09-26 19:03 UTC, patheard commented on terragrunt/aws/api/api_gateway.tf
> +    "method.response.header.Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload"
Same comment about `max-age` ramp up testing.

2021-09-26 19:05 UTC, patheard commented on api/api_gateway/routers/scans.py
> +        return {"error": f"error creating template: {err}"}
Minor nit: `error updating template` instead of `creating`.

2021-09-26 19:06 UTC, patheard commented on api/front_end/static/js/table.js
>      if (typeof (elementExists) == 'undefined' || elementExists == null) {
nit: I realize it's not part of your change, but I'd vote for strict equality here with `===`

2021-09-26 19:15 UTC, patheard requested changes
Good stuff!  Had a few minor comments/questions.

2021-09-26 19:15 UTC, patheard commented on api/front_end/templates/template_scan.html
> +                        <input type='text' name='key' value="{{data.key}}"/>
Could you add an `aria-label="key"` attribute.

2021-09-26 19:15 UTC, patheard commented on api/front_end/templates/template_scan.html
> +                        <input type='text' name='value' value="{{data.value}}"/>
And `aria-label="value"` here.

2021-09-26 19:15 UTC, patheard commented on api/front_end/templates/template_scan_list.html
> +<center>
Instead of the `<center>` element, could you use `<h1 class="text-center">`?

2021-09-26 19:15 UTC, patheard commented on api/front_end/templates/template_scan_list.html
> +    <br/>
Same comment about margin classes vs. `<br>`

2021-09-26 19:15 UTC, patheard commented on api/front_end/templates/template_scan.html
> +    <br/>
nit: if possible use margin CSS classes instead of the `<br>` element.

2021-09-26 19:15 UTC, patheard commented on api/front_end/view.py
> +        # Currently only allow once template scan per template
nit: `one` instead of `once`

2021-09-27 17:52 UTC, mohamed-cds commented on terragrunt/aws/api/api_gateway.tf
> +    "method.response.header.Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload"
Thanks! Great idea. I've changed it to the shortest duration

2021-09-27 17:53 UTC, mohamed-cds commented on api/api_gateway/routers/scans.py
> +        return {"error": f"error creating template: {err}"}
fixed

2021-09-27 17:56 UTC, mohamed-cds commented on api/front_end/static/js/table.js
>      if (typeof (elementExists) == 'undefined' || elementExists == null) {
fixed

2021-09-27 17:56 UTC, mohamed-cds commented on api/front_end/templates/template_scan.html
> +                        <input type='text' name='key' value="{{data.key}}"/>
added

2021-09-27 17:56 UTC, mohamed-cds commented on api/front_end/templates/template_scan.html
> +                        <input type='text' name='value' value="{{data.value}}"/>
added

2021-09-27 17:56 UTC, mohamed-cds commented on api/front_end/templates/template_scan_list.html
> +<center>
changed

2021-09-27 17:56 UTC, mohamed-cds commented on api/front_end/templates/template_scan_list.html
> +    <br/>
changed

2021-09-27 19:30 UTC, patheard commented on api/front_end/templates/template_scan.html
> +  <div class="row margin-bottom: 2em;">
I don't think this will work - you've got a `style` definition in a `class` attribute.  Should be:
```html
<div class="row" style="margin-bottom: 2em;">
``` 
I haven't used Tailwind, but you might be able to make it work like so:
```html
<div class="row mb-8">
```

2021-09-27 19:30 UTC, patheard commented on api/front_end/templates/template_scan_list.html
> +  <div class="row margin-bottom: 2em;">
Same comment about `style` vs `class`

2021-09-27 19:37 UTC, patheard approved these changes
Two really minor CSS gotchas, but nothing that would prevent a merge 🎉

2021-09-27 20:21 UTC, merged