* Update readme.md to help new Devs playing in the project.
cds-snc/scan-websites pull request #348
Opened 2022-06-30 15:06 UTC by ShadeWyrm

# Summary | Résumé

Adds a small tweak to the readme.md for new devs.

# Test instructions | Instructions pour tester la modification

N/A

2022-06-30 16:16 UTC, CalvinRodo requested changes
Please see comments

2022-06-30 16:16 UTC, CalvinRodo commented on README.md
> +`cd api && make install && make install-dev`
This should be able to be run from the root folder as that makefile will send calls to all the makefiles identified in the folders set in this variable

https://github.com/cds-snc/scan-websites/blob/0c25816adf21a7904379f699d5c3ab0907b48c9e/Makefile#L1

The user should be able to just run `make install && make install-dev`

2022-06-30 16:16 UTC, CalvinRodo commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
Curious why this is needed? What tools are in the vscode .local/bin that are required for working with this tool. 

I don't have a ~/vscode/.local/bin/ folder. 

Any required tools for this project should probably be added in the devcontainer.

2022-06-30 16:43 UTC, ShadeWyrm commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
On my fresh install, VSCode wasn't associating the DevContainer Venv as part of PATH. Could be a local issue for me, or something special with the way the ARM version is run. 

Perhaps I add a note if DevContainer isn't adding the dev tools to the PATH that it can be run.

2022-06-30 17:10 UTC, mohamed-cds commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
that's interesting. `/usr/local/bin` should contain the same items as `~/vscode/.local/bin`. I just checked my containers path and it doesnt include `/home/vscode`. Does your path include `/usr/local/bin` @ShadeWyrm ?

I have a vague memory of a `PATH` issue but i can't remember which devcontainer that was

2022-06-30 17:46 UTC, ShadeWyrm commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
PATH contains /usr/local/bin but VSCode's DevContainer Extension was pushing PIP to install to ~/vscode/.local/bin, and for me they're two separate paths. 

~/vscode/.local/bin points to:
/home/vscode/vscode/.local/bin

For me.

2022-06-30 17:51 UTC, mohamed-cds commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
super weird that your home has another subfolder named `vscode` considering the [devcontainer dockerfile](https://github.com/cds-snc/scan-websites/blob/0c25816adf21a7904379f699d5c3ab0907b48c9e/.devcontainer/Dockerfile#L99) ends with `ENV PATH=/home/vscode/.local/bin/:${PATH}`

2022-06-30 18:21 UTC, ShadeWyrm commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
So a quirk of my machine maybe? Shall I remove this note? :)

2022-07-07 18:02 UTC, mohamed-cds commented on README.md
> +`export PATH="$PATH:/home/vscode/.local/bin/"`
@ShadeWyrm sorry for the late response. i rebuilt my container and ran into similar issues. I think i was manually fixing the path. I've tracked down why the PATH variable has been causing us grief and will be fixed by https://github.com/cds-snc/scan-websites/pull/350

2022-07-11 17:51 UTC, mohamed-cds approved these changes
LGTM 🚀 ✅

2022-07-12 20:26 UTC, merged